#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validateAccess } from "./access.js";
import { directTaskPrompt, founderIntakePrompt } from "./prompts.js";

const VERSION = "1.0.0";
const currentFile = fileURLToPath(import.meta.url);
const packageRoot = path.resolve(path.dirname(currentFile), "..");
const home = os.homedir();
const BASELINE_ARTIFACTS = [
  "FOUNDER_PROFILE.md",
  "PRODUCT_CONTEXT.md",
  "LANGUAGE_STRATEGY.md",
  "STACK_DECISION.md",
  "ORGANIC_GROWTH_STRATEGY.md",
  "NINETY_POST_PLAN.md",
  "EDITORIAL_CALENDAR.md",
  "DISTRIBUTION_PLAN.md",
  "TRIGGER_PLAN.md",
  "WORKER_ROUTING.md",
  "MEASUREMENT_PLAN.md",
  "EXECUTION_STATE.md",
];

type Marketplace = {
  name?: string;
  interface?: { displayName?: string };
  plugins?: Array<Record<string, unknown> & { name?: string }>;
};

function help(): void {
  console.log(`Drax Plugin ${VERSION}

Usage:
  drax                         Start founder intelligence intake in Codex
  drax "task"                  Run Drax direct-task mode
  drax init                    Copy the 12 baseline artifacts into the current workspace
  drax blog init               Generate a self-contained Astro editorial blog surface
  drax prompt "task"           Print a portable Drax prompt
  drax install --target all    Install Codex plugin, Claude command, and shell launcher
  drax doctor                  Verify the local installation
  drax --version               Print version
`);
}

function backupIfNeeded(target: string): void {
  if (!existsSync(target)) return;
  const backup = `${target}.user-backup-${new Date().toISOString().replaceAll(/[:.]/g, "-")}`;
  renameSync(target, backup);
}

function isDraxGenerated(content: string): boolean {
  return content.includes("Generated by Drax Plugin") || content.includes("Generated by Drax Corp");
}

function bundlePath(...parts: string[]): string {
  const target = path.join(packageRoot, ...parts);
  if (!existsSync(target)) {
    throw new Error(`Package asset is unavailable: ${target}. Run install from the source package.`);
  }
  return target;
}

function hasFlag(args: string[], flag: string): boolean {
  return args.includes(flag);
}

function optionValue(args: string[], flag: string): string | null {
  const index = args.indexOf(flag);
  if (index < 0) return null;
  const value = args[index + 1];
  return value && !value.startsWith("--") ? value : null;
}

function escapeRegExp(value: string): string {
  return value.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function readWorkspaceArtifact(cwd: string, file: string): string {
  const target = path.join(cwd, file);
  return existsSync(target) ? readFileSync(target, "utf8") : "";
}

function artifactField(content: string, label: string): string | null {
  const match = content.match(new RegExp(`^-\\s+${escapeRegExp(label)}:\\s*(.*)$`, "im"));
  const value = match?.[1]?.trim();
  if (!value) return null;
  return value.replace(/^`(.+)`$/, "$1").trim() || null;
}

function founderBlogConfig(cwd: string): Record<string, string> {
  const distributionPlan = readWorkspaceArtifact(cwd, "DISTRIBUTION_PLAN.md");
  const productContext = readWorkspaceArtifact(cwd, "PRODUCT_CONTEXT.md");
  return {
    SITE_NAME: artifactField(distributionPlan, "Editorial site name") || "NEEDS_DECISION",
    SITE_URL:
      artifactField(distributionPlan, "Canonical site URL") ||
      artifactField(productContext, "Live URL") ||
      "NEEDS_DECISION",
    SITE_DESCRIPTION: artifactField(distributionPlan, "Editorial description") || "NEEDS_DECISION",
    MOUNT_MODE: artifactField(distributionPlan, "Blog attachment mode") || "NEEDS_DECISION",
    BASE_PATH: artifactField(distributionPlan, "Public base path") || "NEEDS_DECISION",
  };
}

function requireRuntimeAccess(): boolean {
  const result = validateAccess(process.cwd());
  if (result.ok) return true;
  console.error(["Drax access token validation failed.", ...result.errors].join("\n"));
  process.exitCode = 1;
  return false;
}

function copyBaselineArtifacts(cwd: string, force: boolean): { created: number; skipped: number } {
  let created = 0;
  let skipped = 0;
  for (const artifact of BASELINE_ARTIFACTS) {
    const source = bundlePath("templates", artifact);
    const target = path.join(cwd, artifact);
    if (existsSync(target) && !force) {
      skipped += 1;
      continue;
    }
    copyFileSync(source, target);
    created += 1;
  }
  return { created, skipped };
}

function initWorkspace(args: string[]): void {
  if (!requireRuntimeAccess()) return;
  const force = hasFlag(args, "--force");
  const { created, skipped } = copyBaselineArtifacts(process.cwd(), force);
  console.log(`Drax baseline artifacts ready. Created: ${created}. Skipped: ${skipped}.`);
  console.log("Next: run `drax` from this workspace and answer one intake question at a time.");
}

function readMarketplace(target: string): Marketplace {
  if (!existsSync(target)) {
    return { name: "personal", interface: { displayName: "Personal" }, plugins: [] };
  }
  const parsed = JSON.parse(readFileSync(target, "utf8")) as Marketplace;
  parsed.plugins ??= [];
  parsed.interface ??= { displayName: "Personal" };
  parsed.name ??= "personal";
  return parsed;
}

function installCodex(): void {
  const pluginSource = bundlePath("plugins", "drax");
  const pluginTarget = path.join(home, "plugins", "drax");
  const marketplacePath = path.join(home, ".agents", "plugins", "marketplace.json");

  mkdirSync(path.dirname(pluginTarget), { recursive: true });
  if (existsSync(pluginTarget)) {
    if (!existsSync(path.join(pluginTarget, ".drax-installer-owned"))) {
      backupIfNeeded(pluginTarget);
    } else {
      rmSync(pluginTarget, { recursive: true, force: true });
    }
  }
  cpSync(pluginSource, pluginTarget, { recursive: true, force: true });
  writeFileSync(path.join(pluginTarget, ".drax-installer-owned"), `${VERSION}\n`, "utf8");

  mkdirSync(path.dirname(marketplacePath), { recursive: true });
  const marketplace = readMarketplace(marketplacePath);
  marketplace.plugins = (marketplace.plugins ?? []).filter((entry) => entry.name !== "drax");
  marketplace.plugins.push({
    name: "drax",
    source: { source: "local", path: "./plugins/drax" },
    policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
    category: "Productivity",
  });
  writeFileSync(marketplacePath, `${JSON.stringify(marketplace, null, 2)}\n`, "utf8");
}

function installClaude(): void {
  const source = bundlePath("compat", "claude", "commands", "drax.md");
  const target = path.join(home, ".claude", "commands", "drax.md");
  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  copyFileSync(source, target);
}

function installLauncher(): void {
  const runtimeRoot = path.join(home, ".local", "share", "drax-plugin");
  const target = path.join(home, ".local", "bin", "drax");
  const assets = ["dist", "plugins", "compat", "templates", "schemas"];

  mkdirSync(runtimeRoot, { recursive: true });
  for (const asset of assets) {
    const assetTarget = path.join(runtimeRoot, asset);
    rmSync(assetTarget, { recursive: true, force: true });
    cpSync(bundlePath(asset), assetTarget, { recursive: true, force: true });
  }

  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  writeFileSync(
    target,
    `#!/bin/sh\n# Generated by Drax Plugin ${VERSION}\nexec "${process.execPath}" "${path.join(runtimeRoot, "dist", "cli.js")}" "$@"\n`,
    "utf8",
  );
  chmodSync(target, 0o755);
}

function install(target: string): void {
  if (!["all", "codex", "claude"].includes(target)) {
    throw new Error(`Unknown install target: ${target}`);
  }
  if (target === "all" || target === "codex") installCodex();
  if (target === "all" || target === "claude") installClaude();
  installLauncher();
  console.log(`Installed Drax Plugin ${VERSION} for ${target}.`);
  console.log("Non-root setup: ensure ~/.local/bin is on PATH before running `drax`.");
  console.log("Codex setup: run `codex login` and complete Device Code login before the first Drax session.");
  console.log("Live publishing remains disabled until a publishing adapter passes its gate.");
}

function doctor(): void {
  const codexBinary = process.env.DRAX_CODEX_BIN || "codex";
  const checks = [
    ["Codex plugin", path.join(home, "plugins", "drax", ".codex-plugin", "plugin.json")],
    ["Codex skill", path.join(home, "plugins", "drax", "skills", "drax", "SKILL.md")],
    ["Personal marketplace", path.join(home, ".agents", "plugins", "marketplace.json")],
    ["Claude command", path.join(home, ".claude", "commands", "drax.md")],
    ["Shell launcher", path.join(home, ".local", "bin", "drax")],
    ["Persistent runtime", path.join(home, ".local", "share", "drax-plugin", "dist", "cli.js")],
  ] as const;
  let ok = true;
  for (const [label, target] of checks) {
    const present = existsSync(target);
    console.log(`${present ? "OK" : "MISSING"} ${label}`);
    ok &&= present;
  }
  for (const [label, binary] of [
    ["Codex CLI", codexBinary],
    ["Python renderer runtime", "python3"],
    ["FFmpeg renderer runtime", "ffmpeg"],
  ] as const) {
    const present = spawnSync(binary, ["--version"], { stdio: "ignore" }).status === 0;
    console.log(`${present ? "OK" : "OPTIONAL-MISSING"} ${label}`);
  }
  console.log(`${process.env.DRAX_ENV_PATH ? "CONFIGURED" : "UNSET"} External environment reference`);
  process.exitCode = ok ? 0 : 1;
}

function replacePlaceholders(content: string, values: Record<string, string>): string {
  return Object.entries(values).reduce((text, [key, value]) => text.replaceAll(`__${key}__`, value), content);
}

function copyBlogTemplate(source: string, target: string, values: Record<string, string>, force: boolean): void {
  const stat = statSync(source);
  if (stat.isDirectory()) {
    mkdirSync(target, { recursive: true });
    for (const entry of readdirSync(source)) {
      copyBlogTemplate(path.join(source, entry), path.join(target, entry), values, force);
    }
    return;
  }
  if (existsSync(target) && !force) return;
  mkdirSync(path.dirname(target), { recursive: true });
  const output = replacePlaceholders(readFileSync(source, "utf8"), values);
  writeFileSync(target, output, "utf8");
}

function initBlog(args: string[]): void {
  if (!requireRuntimeAccess()) return;
  const target = path.resolve(process.cwd(), optionValue(args, "--target") || "drax-blog");
  const force = hasFlag(args, "--force");
  const values = founderBlogConfig(process.cwd());

  copyBlogTemplate(bundlePath("templates", "blog-surface"), target, values, force);
  console.log(`Drax blog surface generated at ${target}`);
  console.log("Next: resolve NEEDS_DECISION values in the founder docs, add posts, then run `npm install` and `npm run build`.");
}

function launchCodex(args: string[]): void {
  if (!requireRuntimeAccess()) return;
  if (!args.length && process.cwd() !== packageRoot) {
    copyBaselineArtifacts(process.cwd(), false);
  }
  const prompt = args.length ? directTaskPrompt(args.join(" ")) : founderIntakePrompt();
  const binary = process.env.DRAX_CODEX_BIN || "codex";
  const result = spawnSync(binary, [prompt], { cwd: process.cwd(), env: process.env, stdio: "inherit" });
  if (result.error) {
    if ("code" in result.error && result.error.code === "ENOENT") {
      console.error("Codex CLI was not found. Add Codex to PATH or set DRAX_CODEX_BIN to the full Codex binary path.");
      console.error("If Codex is not authenticated, run `codex login` and complete Device Code login.");
      process.exitCode = 1;
      return;
    }
    throw result.error;
  }
  process.exitCode = result.status ?? 1;
}

function main(): void {
  const args = process.argv.slice(2);
  const command = args[0];
  if (command === "--help" || command === "-h") return help();
  if (command === "--version" || command === "-v") return console.log(VERSION);
  if (command === "doctor") return doctor();
  if (command === "init") return initWorkspace(args.slice(1));
  if (command === "blog" && args[1] === "init") return initBlog(args.slice(2));
  if (command === "prompt") {
    if (!requireRuntimeAccess()) return;
    return console.log(directTaskPrompt(args.slice(1).join(" ") || "Start Drax."));
  }
  if (command === "install") {
    const targetIndex = args.indexOf("--target");
    return install(targetIndex >= 0 ? args[targetIndex + 1] || "all" : "all");
  }
  if (command === "start") return launchCodex(args.slice(1));
  return launchCodex(args);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
