#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validateAccess } from "./access.js";
import { runCycleCommand } from "./cycle.js";
import { runDistributeCommand } from "./distribute.js";
import { directTaskPrompt, founderIntakePrompt } from "./prompts.js";
import { runStatusCommand } from "./status.js";

const VERSION = "1.1.19";
const currentFile = fileURLToPath(import.meta.url);
const packageRoot = path.resolve(path.dirname(currentFile), "..");
const home = os.homedir();
const BASELINE_ARTIFACTS = [
  "FOUNDER_BRAND_BRIEF.md",
  "BOARD_MANDATE.md",
  "VISION_AND_STRATEGY.md",
  "POSITIONING_STATEMENT.md",
  "MARKET_LOCALIZATION_STRATEGY.md",
  "TECH_DECISION_RECORD.md",
  "GTM_STRATEGY.md",
  "CONTENT_STRATEGY.md",
  "EDITORIAL_CALENDAR.md",
  "CHANNEL_PLAN.md",
  "AUTOMATION_RUNBOOK.md",
  "RESPONSIBILITY_MATRIX.md",
  "MEASUREMENT_FRAMEWORK.md",
  "EXECUTION_STATE.md",
];
const RUNTIME_STATE_FILES = ["EXECUTION_STATE.json"];

type Marketplace = {
  name?: string;
  interface?: { displayName?: string };
  plugins?: Array<Record<string, unknown> & { name?: string }>;
};

function help(): void {
  console.log(`Drax Plugin ${VERSION}

Usage:
  drax                         Start founder intelligence intake in Codex
  drax "task"                  Run Drax direct-task mode
  drax init                    Copy the 14 baseline artifacts into the current workspace
  drax blog init               Generate a self-contained Astro editorial blog surface
  drax cycle --dry-run         Run the headless content cycle without publishing
  drax cycle --publish         Run the headless content cycle and write the blog artifact in the isolated clone
  drax cycle cron              Print the cron entry for the scheduled trigger
  drax distribute login --platform instagram
                               Open a browser once and save a Playwright session
  drax distribute --platform instagram
                               Queue an Instagram post draft from the latest publish record
  drax distribute --platform instagram --confirm
                               Post the queued Instagram single-image feed post
  drax prompt "task"           Print a portable Drax prompt
  drax install --target all    Install Codex plugin, Claude command, and shell launcher
  drax status                  Show funnel layer health (generation, distribution, activation)
  drax status --json           Same as above in machine-readable JSON
  drax doctor                  Verify the local installation
  drax --version               Print version
`);
}

function backupIfNeeded(target: string): void {
  if (!existsSync(target)) return;
  const backup = `${target}.user-backup-${new Date().toISOString().replaceAll(/[:.]/g, "-")}`;
  renameSync(target, backup);
}

function isDraxGenerated(content: string): boolean {
  return content.includes("Generated by Drax Plugin") || content.includes("Generated by Drax Corp");
}

function bundlePath(...parts: string[]): string {
  const target = path.join(packageRoot, ...parts);
  if (!existsSync(target)) {
    throw new Error(`Package asset is unavailable: ${target}. Run install from the source package.`);
  }
  return target;
}

function hasFlag(args: string[], flag: string): boolean {
  return args.includes(flag);
}

function optionValue(args: string[], flag: string): string | null {
  const index = args.indexOf(flag);
  if (index < 0) return null;
  const value = args[index + 1];
  return value && !value.startsWith("--") ? value : null;
}

function escapeRegExp(value: string): string {
  return value.replaceAll(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function readWorkspaceArtifact(cwd: string, file: string): string {
  const target = path.join(cwd, file);
  return existsSync(target) ? readFileSync(target, "utf8") : "";
}

function artifactField(content: string, label: string): string | null {
  const match = content.match(new RegExp(`^-\\s+${escapeRegExp(label)}:\\s*(.*)$`, "im"));
  const value = match?.[1]?.trim();
  if (!value) return null;
  return value.replace(/^`(.+)`$/, "$1").trim() || null;
}

function founderBlogConfig(cwd: string): Record<string, string> {
  const distributionPlan = readWorkspaceArtifact(cwd, "CHANNEL_PLAN.md");
  const productContext = readWorkspaceArtifact(cwd, "POSITIONING_STATEMENT.md");
  return {
    SITE_NAME: artifactField(distributionPlan, "Editorial site name") || "NEEDS_DECISION",
    SITE_URL:
      artifactField(distributionPlan, "Canonical site URL") ||
      artifactField(productContext, "Live URL") ||
      "NEEDS_DECISION",
    SITE_DESCRIPTION: artifactField(distributionPlan, "Editorial description") || "NEEDS_DECISION",
    MOUNT_MODE: artifactField(distributionPlan, "Blog attachment mode") || "NEEDS_DECISION",
    BASE_PATH: artifactField(distributionPlan, "Public base path") || "NEEDS_DECISION",
  };
}

async function requireRuntimeAccess(): Promise<boolean> {
  const result = await validateAccess(process.cwd());
  if (result.ok) return true;
  console.error(["Drax access token validation failed.", ...result.errors].join("\n"));
  process.exitCode = 1;
  return false;
}

function copyBaselineArtifacts(cwd: string, force: boolean): { created: number; skipped: number } {
  let created = 0;
  let skipped = 0;
  for (const artifact of BASELINE_ARTIFACTS) {
    const source = bundlePath("templates", artifact);
    const target = path.join(cwd, artifact);
    if (existsSync(target) && !force) {
      skipped += 1;
      continue;
    }
    copyFileSync(source, target);
    created += 1;
  }
  for (const artifact of RUNTIME_STATE_FILES) {
    const source = bundlePath("templates", artifact);
    const target = path.join(cwd, artifact);
    if (existsSync(target) && !force) {
      skipped += 1;
      continue;
    }
    copyFileSync(source, target);
    created += 1;
  }
  return { created, skipped };
}

async function initWorkspace(args: string[]): Promise<void> {
  if (!(await requireRuntimeAccess())) return;
  const force = hasFlag(args, "--force");
  const { created, skipped } = copyBaselineArtifacts(process.cwd(), force);
  console.log(`Drax baseline artifacts ready. Created: ${created}. Skipped: ${skipped}.`);
  console.log("Next: run `drax` from this workspace and answer one intake question at a time.");
}

function readMarketplace(target: string): Marketplace {
  if (!existsSync(target)) {
    return { name: "personal", interface: { displayName: "Personal" }, plugins: [] };
  }
  const parsed = JSON.parse(readFileSync(target, "utf8")) as Marketplace;
  parsed.plugins ??= [];
  parsed.interface ??= { displayName: "Personal" };
  parsed.name ??= "personal";
  return parsed;
}

function installCodex(): void {
  const pluginSource = bundlePath("plugins", "drax");
  const pluginTarget = path.join(home, "plugins", "drax");
  const marketplacePath = path.join(home, ".agents", "plugins", "marketplace.json");

  mkdirSync(path.dirname(pluginTarget), { recursive: true });
  if (existsSync(pluginTarget)) {
    if (!existsSync(path.join(pluginTarget, ".drax-installer-owned"))) {
      backupIfNeeded(pluginTarget);
    } else {
      rmSync(pluginTarget, { recursive: true, force: true });
    }
  }
  cpSync(pluginSource, pluginTarget, { recursive: true, force: true });
  writeFileSync(path.join(pluginTarget, ".drax-installer-owned"), `${VERSION}\n`, "utf8");

  mkdirSync(path.dirname(marketplacePath), { recursive: true });
  const marketplace = readMarketplace(marketplacePath);
  marketplace.plugins = (marketplace.plugins ?? []).filter((entry) => entry.name !== "drax");
  marketplace.plugins.push({
    name: "drax",
    source: { source: "local", path: "./plugins/drax" },
    policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
    category: "Productivity",
  });
  writeFileSync(marketplacePath, `${JSON.stringify(marketplace, null, 2)}\n`, "utf8");
}

function installClaude(): void {
  const source = bundlePath("compat", "claude", "commands", "drax.md");
  const target = path.join(home, ".claude", "commands", "drax.md");
  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  copyFileSync(source, target);
}

function installLauncher(): void {
  const runtimeRoot = path.join(home, ".local", "share", "drax-plugin");
  const target = path.join(home, ".local", "bin", "drax");
  const assets = ["dist", "plugins", "compat", "templates", "schemas", "scripts", "requirements.txt"];

  mkdirSync(runtimeRoot, { recursive: true });
  for (const asset of assets) {
    const assetTarget = path.join(runtimeRoot, asset);
    rmSync(assetTarget, { recursive: true, force: true });
    cpSync(bundlePath(asset), assetTarget, { recursive: true, force: true });
  }

  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  writeFileSync(
    target,
    `#!/bin/sh\n# Generated by Drax Plugin ${VERSION}\nexec "${process.execPath}" "${path.join(runtimeRoot, "dist", "cli.js")}" "$@"\n`,
    "utf8",
  );
  chmodSync(target, 0o755);
}

function install(target: string): void {
  if (!["all", "codex", "claude"].includes(target)) {
    throw new Error(`Unknown install target: ${target}`);
  }
  if (target === "all" || target === "codex") installCodex();
  if (target === "all" || target === "claude") installClaude();
  installLauncher();
  console.log(`Installed Drax Plugin ${VERSION} for ${target}.`);
  console.log("Non-root setup: ensure ~/.local/bin is on PATH before running `drax`.");
  console.log("Codex setup: run `codex login` and complete Device Code login before the first Drax session.");
  console.log("Live publishing remains disabled until a publishing adapter passes its gate.");
}

function doctor(): void {
  const codexBinary = process.env.DRAX_CODEX_BIN || "codex";
  const surfaces = [
    ["Codex surface", [
      ["Codex plugin", path.join(home, "plugins", "drax", ".codex-plugin", "plugin.json")],
      ["Codex skill", path.join(home, "plugins", "drax", "skills", "drax", "SKILL.md")],
      ["Personal marketplace", path.join(home, ".agents", "plugins", "marketplace.json")],
    ]],
    ["Claude surface", [
      ["Claude command", path.join(home, ".claude", "commands", "drax.md")],
    ]],
  ] as const;
  const installedSurfaces: string[] = [];
  const partialSurfaces: string[] = [];
  for (const [surface, markers] of surfaces) {
    let presentCount = 0;
    for (const [label, target] of markers) {
      const present = existsSync(target);
      console.log(`${present ? "OK" : "MISSING"} ${label}`);
      if (present) presentCount += 1;
    }
    if (presentCount === markers.length) installedSurfaces.push(surface);
    else if (presentCount > 0) partialSurfaces.push(surface);
  }
  const launcherPresent = existsSync(path.join(home, ".local", "bin", "drax"));
  console.log(`${launcherPresent ? "OK" : "MISSING (optional)"} Shell launcher`);
  let runtimePresent = true;
  try {
    bundlePath("templates");
    bundlePath("templates", "workers", "claims-quality-reviewer.md");
  } catch {
    runtimePresent = false;
  }
  console.log(`${runtimePresent ? "OK" : "MISSING"} Bundled runtime assets`);
  const installFlowRuntimePresent = existsSync(path.join(home, ".local", "share", "drax-plugin", "dist", "cli.js"));
  console.log(`${installFlowRuntimePresent ? "OK" : "absent (standalone/global install)"} Install-flow runtime root`);
  if (!installedSurfaces.length && !partialSurfaces.length) {
    console.log("No marketplace surface installed - standalone CLI mode (drax runs headless via codex exec).");
  }
  const failures = [
    ...(!runtimePresent ? ["bundled runtime assets are missing or corrupt"] : []),
    ...partialSurfaces.map((surface) => `${surface} is partial`),
  ];
  for (const [label, binary, versionArg] of [
    ["Codex CLI", codexBinary, "--version"],
    ["Python renderer runtime (social images and video)", "python3", "--version"],
    // ffmpeg uses single-dash `-version`; `--version` exits non-zero and false-flags it missing.
    ["FFmpeg social video renderer runtime", "ffmpeg", "-version"],
  ] as const) {
    const present = spawnSync(binary, [versionArg], { stdio: "ignore" }).status === 0;
    console.log(`${present ? "OK" : "OPTIONAL-MISSING"} ${label}`);
  }
  const pillowPresent = spawnSync("python3", ["-c", "import PIL"], { stdio: "ignore" }).status === 0;
  console.log(`${pillowPresent ? "OK" : "OPTIONAL-MISSING"} Pillow social image library`);
  const playwrightPresent = spawnSync("node", ["-e", "require.resolve('playwright')"], { stdio: "ignore" }).status === 0;
  console.log(`${playwrightPresent ? "OK" : "OPTIONAL-MISSING"} Playwright social posting library`);
  console.log(`${process.env.DRAX_ENV_PATH ? "CONFIGURED" : "UNSET"} External environment reference`);
  console.log(
    failures.length
      ? `Drax install: FAILED - ${failures.join("; ")}`
      : `Drax install: OK (${installedSurfaces.length ? installedSurfaces.join(", ") : "standalone CLI"})`,
  );
  process.exitCode = failures.length ? 1 : 0;
}

function replacePlaceholders(content: string, values: Record<string, string>): string {
  return Object.entries(values).reduce((text, [key, value]) => text.replaceAll(`__${key}__`, value), content);
}

function copyBlogTemplate(source: string, target: string, values: Record<string, string>, force: boolean): void {
  const stat = statSync(source);
  if (stat.isDirectory()) {
    mkdirSync(target, { recursive: true });
    for (const entry of readdirSync(source)) {
      copyBlogTemplate(path.join(source, entry), path.join(target, entry), values, force);
    }
    return;
  }
  if (existsSync(target) && !force) return;
  mkdirSync(path.dirname(target), { recursive: true });
  const output = replacePlaceholders(readFileSync(source, "utf8"), values);
  writeFileSync(target, output, "utf8");
}

async function initBlog(args: string[]): Promise<void> {
  if (!(await requireRuntimeAccess())) return;
  const target = path.resolve(process.cwd(), optionValue(args, "--target") || "drax-blog");
  const force = hasFlag(args, "--force");
  const values = founderBlogConfig(process.cwd());

  copyBlogTemplate(bundlePath("templates", "blog-surface"), target, values, force);
  console.log(`Drax blog surface generated at ${target}`);
  console.log("Next: resolve NEEDS_DECISION values in the founder docs, add posts, then run `npm install` and `npm run build`.");
}

async function launchCodex(args: string[]): Promise<void> {
  if (!(await requireRuntimeAccess())) return;
  if (!args.length && process.cwd() !== packageRoot) {
    copyBaselineArtifacts(process.cwd(), false);
  }
  const prompt = args.length ? directTaskPrompt(args.join(" ")) : founderIntakePrompt();
  const binary = process.env.DRAX_CODEX_BIN || "codex";
  const result = spawnSync(binary, [prompt], { cwd: process.cwd(), env: process.env, stdio: "inherit" });
  if (result.error) {
    if ("code" in result.error && result.error.code === "ENOENT") {
      console.error("Codex CLI was not found. Add Codex to PATH or set DRAX_CODEX_BIN to the full Codex binary path.");
      console.error("If Codex is not authenticated, run `codex login` and complete Device Code login.");
      process.exitCode = 1;
      return;
    }
    throw result.error;
  }
  process.exitCode = result.status ?? 1;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];
  if (command === "--help" || command === "-h") return help();
  if (command === "--version" || command === "-v") return console.log(VERSION);
  if (command === "doctor") return doctor();
  if (command === "status") return runStatusCommand(args.slice(1));
  if (command === "init") return initWorkspace(args.slice(1));
  if (command === "blog" && args[1] === "init") return initBlog(args.slice(2));
  if (command === "cycle") {
    if (!(await requireRuntimeAccess())) return;
    process.exitCode = runCycleCommand(args.slice(1), {
      cwd: process.cwd(),
      cliPath: currentFile,
      nodePath: process.execPath,
      env: process.env,
    });
    return;
  }
  if (command === "distribute") {
    if (!(await requireRuntimeAccess())) return;
    process.exitCode = await runDistributeCommand(args.slice(1), { cwd: process.cwd(), env: process.env });
    return;
  }
  if (command === "prompt") {
    if (!(await requireRuntimeAccess())) return;
    return console.log(directTaskPrompt(args.slice(1).join(" ") || "Start Drax."));
  }
  if (command === "install") {
    const targetIndex = args.indexOf("--target");
    return install(targetIndex >= 0 ? args[targetIndex + 1] || "all" : "all");
  }
  if (command === "start") return launchCodex(args.slice(1));
  return launchCodex(args);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
