#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { directTaskPrompt, founderIntakePrompt } from "./prompts.js";

const VERSION = "1.0.0";
const currentFile = fileURLToPath(import.meta.url);
const packageRoot = path.resolve(path.dirname(currentFile), "..");
const home = os.homedir();

type Marketplace = {
  name?: string;
  interface?: { displayName?: string };
  plugins?: Array<Record<string, unknown> & { name?: string }>;
};

function help(): void {
  console.log(`Drax Plugin ${VERSION}

Usage:
  drax                         Start founder intelligence intake in Codex
  drax "task"                  Run Drax direct-task mode
  drax prompt "task"           Print a portable Drax prompt
  drax install --target all    Install Codex plugin, Claude command, and shell launcher
  drax doctor                  Verify the local installation
  drax --version               Print version
`);
}

function backupIfNeeded(target: string): void {
  if (!existsSync(target)) return;
  const backup = `${target}.user-backup-${new Date().toISOString().replaceAll(/[:.]/g, "-")}`;
  renameSync(target, backup);
}

function isDraxGenerated(content: string): boolean {
  return content.includes("Generated by Drax Plugin") || content.includes("Generated by Drax Corp");
}

function bundlePath(...parts: string[]): string {
  const target = path.join(packageRoot, ...parts);
  if (!existsSync(target)) {
    throw new Error(`Package asset is unavailable: ${target}. Run install from the source package.`);
  }
  return target;
}

function readMarketplace(target: string): Marketplace {
  if (!existsSync(target)) {
    return { name: "personal", interface: { displayName: "Personal" }, plugins: [] };
  }
  const parsed = JSON.parse(readFileSync(target, "utf8")) as Marketplace;
  parsed.plugins ??= [];
  parsed.interface ??= { displayName: "Personal" };
  parsed.name ??= "personal";
  return parsed;
}

function installCodex(): void {
  const pluginSource = bundlePath("plugins", "drax");
  const pluginTarget = path.join(home, "plugins", "drax");
  const marketplacePath = path.join(home, ".agents", "plugins", "marketplace.json");

  mkdirSync(path.dirname(pluginTarget), { recursive: true });
  if (existsSync(pluginTarget)) {
    if (!existsSync(path.join(pluginTarget, ".drax-installer-owned"))) {
      backupIfNeeded(pluginTarget);
    } else {
      rmSync(pluginTarget, { recursive: true, force: true });
    }
  }
  cpSync(pluginSource, pluginTarget, { recursive: true, force: true });
  writeFileSync(path.join(pluginTarget, ".drax-installer-owned"), `${VERSION}\n`, "utf8");

  mkdirSync(path.dirname(marketplacePath), { recursive: true });
  const marketplace = readMarketplace(marketplacePath);
  marketplace.plugins = (marketplace.plugins ?? []).filter((entry) => entry.name !== "drax");
  marketplace.plugins.push({
    name: "drax",
    source: { source: "local", path: "./plugins/drax" },
    policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
    category: "Productivity",
  });
  writeFileSync(marketplacePath, `${JSON.stringify(marketplace, null, 2)}\n`, "utf8");
}

function installClaude(): void {
  const source = bundlePath("compat", "claude", "commands", "drax.md");
  const target = path.join(home, ".claude", "commands", "drax.md");
  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  copyFileSync(source, target);
}

function installLauncher(): void {
  const runtimeRoot = path.join(home, ".local", "share", "drax-plugin");
  const target = path.join(home, ".local", "bin", "drax");
  const assets = ["dist", "plugins", "compat", "templates", "schemas"];

  mkdirSync(runtimeRoot, { recursive: true });
  for (const asset of assets) {
    const assetTarget = path.join(runtimeRoot, asset);
    rmSync(assetTarget, { recursive: true, force: true });
    cpSync(bundlePath(asset), assetTarget, { recursive: true, force: true });
  }

  mkdirSync(path.dirname(target), { recursive: true });
  if (existsSync(target) && !isDraxGenerated(readFileSync(target, "utf8"))) {
    backupIfNeeded(target);
  }
  writeFileSync(
    target,
    `#!/bin/sh\n# Generated by Drax Plugin ${VERSION}\nexec "${process.execPath}" "${path.join(runtimeRoot, "dist", "cli.js")}" "$@"\n`,
    "utf8",
  );
  chmodSync(target, 0o755);
}

function install(target: string): void {
  if (!["all", "codex", "claude"].includes(target)) {
    throw new Error(`Unknown install target: ${target}`);
  }
  if (target === "all" || target === "codex") installCodex();
  if (target === "all" || target === "claude") installClaude();
  installLauncher();
  console.log(`Installed Drax Plugin ${VERSION} for ${target}.`);
  console.log("Live publishing remains disabled until a publishing adapter passes its gate.");
}

function doctor(): void {
  const checks = [
    ["Codex plugin", path.join(home, "plugins", "drax", ".codex-plugin", "plugin.json")],
    ["Codex skill", path.join(home, "plugins", "drax", "skills", "drax", "SKILL.md")],
    ["Personal marketplace", path.join(home, ".agents", "plugins", "marketplace.json")],
    ["Claude command", path.join(home, ".claude", "commands", "drax.md")],
    ["Shell launcher", path.join(home, ".local", "bin", "drax")],
    ["Persistent runtime", path.join(home, ".local", "share", "drax-plugin", "dist", "cli.js")],
  ] as const;
  let ok = true;
  for (const [label, target] of checks) {
    const present = existsSync(target);
    console.log(`${present ? "OK" : "MISSING"} ${label}`);
    ok &&= present;
  }
  for (const [label, binary] of [
    ["Python renderer runtime", "python3"],
    ["FFmpeg renderer runtime", "ffmpeg"],
  ] as const) {
    const present = spawnSync(binary, ["--version"], { stdio: "ignore" }).status === 0;
    console.log(`${present ? "OK" : "OPTIONAL-MISSING"} ${label}`);
  }
  console.log(`${process.env.DRAX_ENV_PATH ? "CONFIGURED" : "UNSET"} External environment reference`);
  process.exitCode = ok ? 0 : 1;
}

function launchCodex(args: string[]): void {
  const prompt = args.length ? directTaskPrompt(args.join(" ")) : founderIntakePrompt();
  const binary = process.env.DRAX_CODEX_BIN || "codex";
  const result = spawnSync(binary, [prompt], { cwd: process.cwd(), env: process.env, stdio: "inherit" });
  if (result.error) throw result.error;
  process.exitCode = result.status ?? 1;
}

function main(): void {
  const args = process.argv.slice(2);
  const command = args[0];
  if (command === "--help" || command === "-h") return help();
  if (command === "--version" || command === "-v") return console.log(VERSION);
  if (command === "doctor") return doctor();
  if (command === "prompt") return console.log(directTaskPrompt(args.slice(1).join(" ") || "Start Drax."));
  if (command === "install") {
    const targetIndex = args.indexOf("--target");
    return install(targetIndex >= 0 ? args[targetIndex + 1] || "all" : "all");
  }
  if (command === "start") return launchCodex(args.slice(1));
  return launchCodex(args);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
